DB_ADDRESS: localhost
DB_PORT: 5432
DB_NAME: obgs
DB_USER: postgres
DB_PASS: postgres
JWT_SECRET: secret
SERVER_HOST: localhost
OAUTH_GOOGLE_CLIENT_ID: google_client_id
OAUTH_GOOGLE_CLIENT_SECRET: google_client_secret
S3_ACCESS_KEY_ID: minio
S3_SECRET_ACCESS_KEY: minio123
S3_REGION: eu-east-1
S3_ENDPOINT: http://localhost:9000
S3_BUCKET: obgs-dev
USING_MINIO: true
ENT_DEBUG: true
INTROSPECTION_ENABLED: true
PLAYGROUND_ENABLED: true
