DB_ADDRESS: localhost
DB_PORT: 5432
DB_NAME: obgs
DB_USER: postgres
DB_PASS: postgres
JWT_SECRET: secret
SERVER_HOST: localhost
OAUTH_GOOGLE_CLIENT_ID: google_client_id
OAUTH_GOOGLE_CLIENT_SECRET: google_client_secret
