run:
  timeout: "1m"
  tests: true
  allow-parallel-runners: false
  go: "1.22.4"

issues:
  exclude-use-default: true
  exclude-case-sensitive: false
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  exclude:
    - "/internal/ent"
  include:
    - "/internal/ent/schema"
  exclude-rules:
    - path: "internal/graphql/resolver/*.*.go"
      text: "line is .* characters"
    - path: "internal/graphql/resolver/*.*.go"
      linters:
        - gofumpt
    - path: "internal/ent/migrate/seed/*.*.go"
      linters:
        - gomnd
        - funlen

linters:
  enable-all: true
  disable:
    - wsl
    - godot
    - nosnakecase
    - gochecknoglobals
    - gochecknoinits
    - gci
    - ifshort
    - scopelint

  fast: true

linters-settings:
  nlreturn:
    block-size: 2

output:
  print-issued-lines: true
  print-linter-name: true

severity:
  default-severity: error
  rules:
    - linters:
        - godox
      severity: warning
