version: '3'

tasks:
  create_migration:
    - go run --mod=mod internal/ent/migrate/main.go {{.CLI_ARGS}} "postgresql://postgres:postgres@localhost:5432/test?sslmode=disable"

  apply_migration:
    - atlas migrate apply --dir file://internal/ent/migrate/migrations --url "postgresql://postgres:postgres@localhost:5432/obgs?sslmode=disable"
