// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-boardgame-stats/backend/internal/ent/enumstatdescription"
	"github.com/open-boardgame-stats/backend/internal/ent/game"
	"github.com/open-boardgame-stats/backend/internal/ent/gamefavorite"
	"github.com/open-boardgame-stats/backend/internal/ent/match"
	"github.com/open-boardgame-stats/backend/internal/ent/numericalstatdescription"
	"github.com/open-boardgame-stats/backend/internal/ent/predicate"
	"github.com/open-boardgame-stats/backend/internal/ent/schema/guidgql"
	"github.com/open-boardgame-stats/backend/internal/ent/user"
)

// GameQuery is the builder for querying Game entities.
type GameQuery struct {
	config
	limit                              *int
	offset                             *int
	unique                             *bool
	order                              []OrderFunc
	fields                             []string
	predicates                         []predicate.Game
	withAuthor                         *UserQuery
	withFavorites                      *GameFavoriteQuery
	withNumericalStatDescriptions      *NumericalStatDescriptionQuery
	withEnumStatDescriptions           *EnumStatDescriptionQuery
	withMatches                        *MatchQuery
	withFKs                            bool
	modifiers                          []func(*sql.Selector)
	loadTotal                          []func(context.Context, []*Game) error
	withNamedFavorites                 map[string]*GameFavoriteQuery
	withNamedNumericalStatDescriptions map[string]*NumericalStatDescriptionQuery
	withNamedEnumStatDescriptions      map[string]*EnumStatDescriptionQuery
	withNamedMatches                   map[string]*MatchQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GameQuery builder.
func (gq *GameQuery) Where(ps ...predicate.Game) *GameQuery {
	gq.predicates = append(gq.predicates, ps...)
	return gq
}

// Limit adds a limit step to the query.
func (gq *GameQuery) Limit(limit int) *GameQuery {
	gq.limit = &limit
	return gq
}

// Offset adds an offset step to the query.
func (gq *GameQuery) Offset(offset int) *GameQuery {
	gq.offset = &offset
	return gq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gq *GameQuery) Unique(unique bool) *GameQuery {
	gq.unique = &unique
	return gq
}

// Order adds an order step to the query.
func (gq *GameQuery) Order(o ...OrderFunc) *GameQuery {
	gq.order = append(gq.order, o...)
	return gq
}

// QueryAuthor chains the current query on the "author" edge.
func (gq *GameQuery) QueryAuthor() *UserQuery {
	query := &UserQuery{config: gq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(game.Table, game.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, game.AuthorTable, game.AuthorColumn),
		)
		fromU = sqlgraph.SetNeighbors(gq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFavorites chains the current query on the "favorites" edge.
func (gq *GameQuery) QueryFavorites() *GameFavoriteQuery {
	query := &GameFavoriteQuery{config: gq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(game.Table, game.FieldID, selector),
			sqlgraph.To(gamefavorite.Table, gamefavorite.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, game.FavoritesTable, game.FavoritesColumn),
		)
		fromU = sqlgraph.SetNeighbors(gq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNumericalStatDescriptions chains the current query on the "numerical_stat_descriptions" edge.
func (gq *GameQuery) QueryNumericalStatDescriptions() *NumericalStatDescriptionQuery {
	query := &NumericalStatDescriptionQuery{config: gq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(game.Table, game.FieldID, selector),
			sqlgraph.To(numericalstatdescription.Table, numericalstatdescription.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, game.NumericalStatDescriptionsTable, game.NumericalStatDescriptionsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(gq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEnumStatDescriptions chains the current query on the "enum_stat_descriptions" edge.
func (gq *GameQuery) QueryEnumStatDescriptions() *EnumStatDescriptionQuery {
	query := &EnumStatDescriptionQuery{config: gq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(game.Table, game.FieldID, selector),
			sqlgraph.To(enumstatdescription.Table, enumstatdescription.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, game.EnumStatDescriptionsTable, game.EnumStatDescriptionsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(gq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMatches chains the current query on the "matches" edge.
func (gq *GameQuery) QueryMatches() *MatchQuery {
	query := &MatchQuery{config: gq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(game.Table, game.FieldID, selector),
			sqlgraph.To(match.Table, match.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, game.MatchesTable, game.MatchesColumn),
		)
		fromU = sqlgraph.SetNeighbors(gq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Game entity from the query.
// Returns a *NotFoundError when no Game was found.
func (gq *GameQuery) First(ctx context.Context) (*Game, error) {
	nodes, err := gq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{game.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gq *GameQuery) FirstX(ctx context.Context) *Game {
	node, err := gq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Game ID from the query.
// Returns a *NotFoundError when no Game ID was found.
func (gq *GameQuery) FirstID(ctx context.Context) (id guidgql.GUID, err error) {
	var ids []guidgql.GUID
	if ids, err = gq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{game.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gq *GameQuery) FirstIDX(ctx context.Context) guidgql.GUID {
	id, err := gq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Game entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Game entity is found.
// Returns a *NotFoundError when no Game entities are found.
func (gq *GameQuery) Only(ctx context.Context) (*Game, error) {
	nodes, err := gq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{game.Label}
	default:
		return nil, &NotSingularError{game.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gq *GameQuery) OnlyX(ctx context.Context) *Game {
	node, err := gq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Game ID in the query.
// Returns a *NotSingularError when more than one Game ID is found.
// Returns a *NotFoundError when no entities are found.
func (gq *GameQuery) OnlyID(ctx context.Context) (id guidgql.GUID, err error) {
	var ids []guidgql.GUID
	if ids, err = gq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{game.Label}
	default:
		err = &NotSingularError{game.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gq *GameQuery) OnlyIDX(ctx context.Context) guidgql.GUID {
	id, err := gq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Games.
func (gq *GameQuery) All(ctx context.Context) ([]*Game, error) {
	if err := gq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return gq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (gq *GameQuery) AllX(ctx context.Context) []*Game {
	nodes, err := gq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Game IDs.
func (gq *GameQuery) IDs(ctx context.Context) ([]guidgql.GUID, error) {
	var ids []guidgql.GUID
	if err := gq.Select(game.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gq *GameQuery) IDsX(ctx context.Context) []guidgql.GUID {
	ids, err := gq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gq *GameQuery) Count(ctx context.Context) (int, error) {
	if err := gq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return gq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (gq *GameQuery) CountX(ctx context.Context) int {
	count, err := gq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gq *GameQuery) Exist(ctx context.Context) (bool, error) {
	if err := gq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return gq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (gq *GameQuery) ExistX(ctx context.Context) bool {
	exist, err := gq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GameQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gq *GameQuery) Clone() *GameQuery {
	if gq == nil {
		return nil
	}
	return &GameQuery{
		config:                        gq.config,
		limit:                         gq.limit,
		offset:                        gq.offset,
		order:                         append([]OrderFunc{}, gq.order...),
		predicates:                    append([]predicate.Game{}, gq.predicates...),
		withAuthor:                    gq.withAuthor.Clone(),
		withFavorites:                 gq.withFavorites.Clone(),
		withNumericalStatDescriptions: gq.withNumericalStatDescriptions.Clone(),
		withEnumStatDescriptions:      gq.withEnumStatDescriptions.Clone(),
		withMatches:                   gq.withMatches.Clone(),
		// clone intermediate query.
		sql:    gq.sql.Clone(),
		path:   gq.path,
		unique: gq.unique,
	}
}

// WithAuthor tells the query-builder to eager-load the nodes that are connected to
// the "author" edge. The optional arguments are used to configure the query builder of the edge.
func (gq *GameQuery) WithAuthor(opts ...func(*UserQuery)) *GameQuery {
	query := &UserQuery{config: gq.config}
	for _, opt := range opts {
		opt(query)
	}
	gq.withAuthor = query
	return gq
}

// WithFavorites tells the query-builder to eager-load the nodes that are connected to
// the "favorites" edge. The optional arguments are used to configure the query builder of the edge.
func (gq *GameQuery) WithFavorites(opts ...func(*GameFavoriteQuery)) *GameQuery {
	query := &GameFavoriteQuery{config: gq.config}
	for _, opt := range opts {
		opt(query)
	}
	gq.withFavorites = query
	return gq
}

// WithNumericalStatDescriptions tells the query-builder to eager-load the nodes that are connected to
// the "numerical_stat_descriptions" edge. The optional arguments are used to configure the query builder of the edge.
func (gq *GameQuery) WithNumericalStatDescriptions(opts ...func(*NumericalStatDescriptionQuery)) *GameQuery {
	query := &NumericalStatDescriptionQuery{config: gq.config}
	for _, opt := range opts {
		opt(query)
	}
	gq.withNumericalStatDescriptions = query
	return gq
}

// WithEnumStatDescriptions tells the query-builder to eager-load the nodes that are connected to
// the "enum_stat_descriptions" edge. The optional arguments are used to configure the query builder of the edge.
func (gq *GameQuery) WithEnumStatDescriptions(opts ...func(*EnumStatDescriptionQuery)) *GameQuery {
	query := &EnumStatDescriptionQuery{config: gq.config}
	for _, opt := range opts {
		opt(query)
	}
	gq.withEnumStatDescriptions = query
	return gq
}

// WithMatches tells the query-builder to eager-load the nodes that are connected to
// the "matches" edge. The optional arguments are used to configure the query builder of the edge.
func (gq *GameQuery) WithMatches(opts ...func(*MatchQuery)) *GameQuery {
	query := &MatchQuery{config: gq.config}
	for _, opt := range opts {
		opt(query)
	}
	gq.withMatches = query
	return gq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Game.Query().
//		GroupBy(game.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gq *GameQuery) GroupBy(field string, fields ...string) *GameGroupBy {
	grbuild := &GameGroupBy{config: gq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := gq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return gq.sqlQuery(ctx), nil
	}
	grbuild.label = game.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Game.Query().
//		Select(game.FieldName).
//		Scan(ctx, &v)
func (gq *GameQuery) Select(fields ...string) *GameSelect {
	gq.fields = append(gq.fields, fields...)
	selbuild := &GameSelect{GameQuery: gq}
	selbuild.label = game.Label
	selbuild.flds, selbuild.scan = &gq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a GameSelect configured with the given aggregations.
func (gq *GameQuery) Aggregate(fns ...AggregateFunc) *GameSelect {
	return gq.Select().Aggregate(fns...)
}

func (gq *GameQuery) prepareQuery(ctx context.Context) error {
	for _, f := range gq.fields {
		if !game.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gq.path != nil {
		prev, err := gq.path(ctx)
		if err != nil {
			return err
		}
		gq.sql = prev
	}
	return nil
}

func (gq *GameQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Game, error) {
	var (
		nodes       = []*Game{}
		withFKs     = gq.withFKs
		_spec       = gq.querySpec()
		loadedTypes = [5]bool{
			gq.withAuthor != nil,
			gq.withFavorites != nil,
			gq.withNumericalStatDescriptions != nil,
			gq.withEnumStatDescriptions != nil,
			gq.withMatches != nil,
		}
	)
	if gq.withAuthor != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, game.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Game).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Game{config: gq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(gq.modifiers) > 0 {
		_spec.Modifiers = gq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := gq.withAuthor; query != nil {
		if err := gq.loadAuthor(ctx, query, nodes, nil,
			func(n *Game, e *User) { n.Edges.Author = e }); err != nil {
			return nil, err
		}
	}
	if query := gq.withFavorites; query != nil {
		if err := gq.loadFavorites(ctx, query, nodes,
			func(n *Game) { n.Edges.Favorites = []*GameFavorite{} },
			func(n *Game, e *GameFavorite) { n.Edges.Favorites = append(n.Edges.Favorites, e) }); err != nil {
			return nil, err
		}
	}
	if query := gq.withNumericalStatDescriptions; query != nil {
		if err := gq.loadNumericalStatDescriptions(ctx, query, nodes,
			func(n *Game) { n.Edges.NumericalStatDescriptions = []*NumericalStatDescription{} },
			func(n *Game, e *NumericalStatDescription) {
				n.Edges.NumericalStatDescriptions = append(n.Edges.NumericalStatDescriptions, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := gq.withEnumStatDescriptions; query != nil {
		if err := gq.loadEnumStatDescriptions(ctx, query, nodes,
			func(n *Game) { n.Edges.EnumStatDescriptions = []*EnumStatDescription{} },
			func(n *Game, e *EnumStatDescription) {
				n.Edges.EnumStatDescriptions = append(n.Edges.EnumStatDescriptions, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := gq.withMatches; query != nil {
		if err := gq.loadMatches(ctx, query, nodes,
			func(n *Game) { n.Edges.Matches = []*Match{} },
			func(n *Game, e *Match) { n.Edges.Matches = append(n.Edges.Matches, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range gq.withNamedFavorites {
		if err := gq.loadFavorites(ctx, query, nodes,
			func(n *Game) { n.appendNamedFavorites(name) },
			func(n *Game, e *GameFavorite) { n.appendNamedFavorites(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range gq.withNamedNumericalStatDescriptions {
		if err := gq.loadNumericalStatDescriptions(ctx, query, nodes,
			func(n *Game) { n.appendNamedNumericalStatDescriptions(name) },
			func(n *Game, e *NumericalStatDescription) { n.appendNamedNumericalStatDescriptions(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range gq.withNamedEnumStatDescriptions {
		if err := gq.loadEnumStatDescriptions(ctx, query, nodes,
			func(n *Game) { n.appendNamedEnumStatDescriptions(name) },
			func(n *Game, e *EnumStatDescription) { n.appendNamedEnumStatDescriptions(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range gq.withNamedMatches {
		if err := gq.loadMatches(ctx, query, nodes,
			func(n *Game) { n.appendNamedMatches(name) },
			func(n *Game, e *Match) { n.appendNamedMatches(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range gq.loadTotal {
		if err := gq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (gq *GameQuery) loadAuthor(ctx context.Context, query *UserQuery, nodes []*Game, init func(*Game), assign func(*Game, *User)) error {
	ids := make([]guidgql.GUID, 0, len(nodes))
	nodeids := make(map[guidgql.GUID][]*Game)
	for i := range nodes {
		if nodes[i].user_games == nil {
			continue
		}
		fk := *nodes[i].user_games
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_games" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (gq *GameQuery) loadFavorites(ctx context.Context, query *GameFavoriteQuery, nodes []*Game, init func(*Game), assign func(*Game, *GameFavorite)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[guidgql.GUID]*Game)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.GameFavorite(func(s *sql.Selector) {
		s.Where(sql.InValues(game.FavoritesColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.game_favorites
		if fk == nil {
			return fmt.Errorf(`foreign-key "game_favorites" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "game_favorites" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (gq *GameQuery) loadNumericalStatDescriptions(ctx context.Context, query *NumericalStatDescriptionQuery, nodes []*Game, init func(*Game), assign func(*Game, *NumericalStatDescription)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[guidgql.GUID]*Game)
	nids := make(map[guidgql.GUID]map[*Game]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(game.NumericalStatDescriptionsTable)
		s.Join(joinT).On(s.C(numericalstatdescription.FieldID), joinT.C(game.NumericalStatDescriptionsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(game.NumericalStatDescriptionsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(game.NumericalStatDescriptionsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(guidgql.GUID)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := *values[0].(*guidgql.GUID)
			inValue := *values[1].(*guidgql.GUID)
			if nids[inValue] == nil {
				nids[inValue] = map[*Game]struct{}{byID[outValue]: {}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "numerical_stat_descriptions" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (gq *GameQuery) loadEnumStatDescriptions(ctx context.Context, query *EnumStatDescriptionQuery, nodes []*Game, init func(*Game), assign func(*Game, *EnumStatDescription)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[guidgql.GUID]*Game)
	nids := make(map[guidgql.GUID]map[*Game]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(game.EnumStatDescriptionsTable)
		s.Join(joinT).On(s.C(enumstatdescription.FieldID), joinT.C(game.EnumStatDescriptionsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(game.EnumStatDescriptionsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(game.EnumStatDescriptionsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	neighbors, err := query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
		assign := spec.Assign
		values := spec.ScanValues
		spec.ScanValues = func(columns []string) ([]any, error) {
			values, err := values(columns[1:])
			if err != nil {
				return nil, err
			}
			return append([]any{new(guidgql.GUID)}, values...), nil
		}
		spec.Assign = func(columns []string, values []any) error {
			outValue := *values[0].(*guidgql.GUID)
			inValue := *values[1].(*guidgql.GUID)
			if nids[inValue] == nil {
				nids[inValue] = map[*Game]struct{}{byID[outValue]: {}}
				return assign(columns[1:], values[1:])
			}
			nids[inValue][byID[outValue]] = struct{}{}
			return nil
		}
	})
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "enum_stat_descriptions" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (gq *GameQuery) loadMatches(ctx context.Context, query *MatchQuery, nodes []*Game, init func(*Game), assign func(*Game, *Match)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[guidgql.GUID]*Game)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Match(func(s *sql.Selector) {
		s.Where(sql.InValues(game.MatchesColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.game_matches
		if fk == nil {
			return fmt.Errorf(`foreign-key "game_matches" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "game_matches" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (gq *GameQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gq.querySpec()
	if len(gq.modifiers) > 0 {
		_spec.Modifiers = gq.modifiers
	}
	_spec.Node.Columns = gq.fields
	if len(gq.fields) > 0 {
		_spec.Unique = gq.unique != nil && *gq.unique
	}
	return sqlgraph.CountNodes(ctx, gq.driver, _spec)
}

func (gq *GameQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := gq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (gq *GameQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   game.Table,
			Columns: game.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: game.FieldID,
			},
		},
		From:   gq.sql,
		Unique: true,
	}
	if unique := gq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := gq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, game.FieldID)
		for i := range fields {
			if fields[i] != game.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gq *GameQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gq.driver.Dialect())
	t1 := builder.Table(game.Table)
	columns := gq.fields
	if len(columns) == 0 {
		columns = game.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gq.sql != nil {
		selector = gq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gq.unique != nil && *gq.unique {
		selector.Distinct()
	}
	for _, p := range gq.predicates {
		p(selector)
	}
	for _, p := range gq.order {
		p(selector)
	}
	if offset := gq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedFavorites tells the query-builder to eager-load the nodes that are connected to the "favorites"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (gq *GameQuery) WithNamedFavorites(name string, opts ...func(*GameFavoriteQuery)) *GameQuery {
	query := &GameFavoriteQuery{config: gq.config}
	for _, opt := range opts {
		opt(query)
	}
	if gq.withNamedFavorites == nil {
		gq.withNamedFavorites = make(map[string]*GameFavoriteQuery)
	}
	gq.withNamedFavorites[name] = query
	return gq
}

// WithNamedNumericalStatDescriptions tells the query-builder to eager-load the nodes that are connected to the "numerical_stat_descriptions"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (gq *GameQuery) WithNamedNumericalStatDescriptions(name string, opts ...func(*NumericalStatDescriptionQuery)) *GameQuery {
	query := &NumericalStatDescriptionQuery{config: gq.config}
	for _, opt := range opts {
		opt(query)
	}
	if gq.withNamedNumericalStatDescriptions == nil {
		gq.withNamedNumericalStatDescriptions = make(map[string]*NumericalStatDescriptionQuery)
	}
	gq.withNamedNumericalStatDescriptions[name] = query
	return gq
}

// WithNamedEnumStatDescriptions tells the query-builder to eager-load the nodes that are connected to the "enum_stat_descriptions"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (gq *GameQuery) WithNamedEnumStatDescriptions(name string, opts ...func(*EnumStatDescriptionQuery)) *GameQuery {
	query := &EnumStatDescriptionQuery{config: gq.config}
	for _, opt := range opts {
		opt(query)
	}
	if gq.withNamedEnumStatDescriptions == nil {
		gq.withNamedEnumStatDescriptions = make(map[string]*EnumStatDescriptionQuery)
	}
	gq.withNamedEnumStatDescriptions[name] = query
	return gq
}

// WithNamedMatches tells the query-builder to eager-load the nodes that are connected to the "matches"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (gq *GameQuery) WithNamedMatches(name string, opts ...func(*MatchQuery)) *GameQuery {
	query := &MatchQuery{config: gq.config}
	for _, opt := range opts {
		opt(query)
	}
	if gq.withNamedMatches == nil {
		gq.withNamedMatches = make(map[string]*MatchQuery)
	}
	gq.withNamedMatches[name] = query
	return gq
}

// GameGroupBy is the group-by builder for Game entities.
type GameGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ggb *GameGroupBy) Aggregate(fns ...AggregateFunc) *GameGroupBy {
	ggb.fns = append(ggb.fns, fns...)
	return ggb
}

// Scan applies the group-by query and scans the result into the given value.
func (ggb *GameGroupBy) Scan(ctx context.Context, v any) error {
	query, err := ggb.path(ctx)
	if err != nil {
		return err
	}
	ggb.sql = query
	return ggb.sqlScan(ctx, v)
}

func (ggb *GameGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range ggb.fields {
		if !game.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ggb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ggb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ggb *GameGroupBy) sqlQuery() *sql.Selector {
	selector := ggb.sql.Select()
	aggregation := make([]string, 0, len(ggb.fns))
	for _, fn := range ggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ggb.fields)+len(ggb.fns))
		for _, f := range ggb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ggb.fields...)...)
}

// GameSelect is the builder for selecting fields of Game entities.
type GameSelect struct {
	*GameQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (gs *GameSelect) Aggregate(fns ...AggregateFunc) *GameSelect {
	gs.fns = append(gs.fns, fns...)
	return gs
}

// Scan applies the selector query and scans the result into the given value.
func (gs *GameSelect) Scan(ctx context.Context, v any) error {
	if err := gs.prepareQuery(ctx); err != nil {
		return err
	}
	gs.sql = gs.GameQuery.sqlQuery(ctx)
	return gs.sqlScan(ctx, v)
}

func (gs *GameSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(gs.fns))
	for _, fn := range gs.fns {
		aggregation = append(aggregation, fn(gs.sql))
	}
	switch n := len(*gs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		gs.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		gs.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := gs.sql.Query()
	if err := gs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
