// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-boardgame-stats/backend/internal/ent/groupmembershipapplication"
	"github.com/open-boardgame-stats/backend/internal/ent/predicate"
)

// GroupMembershipApplicationDelete is the builder for deleting a GroupMembershipApplication entity.
type GroupMembershipApplicationDelete struct {
	config
	hooks    []Hook
	mutation *GroupMembershipApplicationMutation
}

// Where appends a list predicates to the GroupMembershipApplicationDelete builder.
func (gmad *GroupMembershipApplicationDelete) Where(ps ...predicate.GroupMembershipApplication) *GroupMembershipApplicationDelete {
	gmad.mutation.Where(ps...)
	return gmad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gmad *GroupMembershipApplicationDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gmad.hooks) == 0 {
		affected, err = gmad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroupMembershipApplicationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gmad.mutation = mutation
			affected, err = gmad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gmad.hooks) - 1; i >= 0; i-- {
			if gmad.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gmad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gmad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (gmad *GroupMembershipApplicationDelete) ExecX(ctx context.Context) int {
	n, err := gmad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gmad *GroupMembershipApplicationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: groupmembershipapplication.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: groupmembershipapplication.FieldID,
			},
		},
	}
	if ps := gmad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gmad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// GroupMembershipApplicationDeleteOne is the builder for deleting a single GroupMembershipApplication entity.
type GroupMembershipApplicationDeleteOne struct {
	gmad *GroupMembershipApplicationDelete
}

// Exec executes the deletion query.
func (gmado *GroupMembershipApplicationDeleteOne) Exec(ctx context.Context) error {
	n, err := gmado.gmad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupmembershipapplication.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gmado *GroupMembershipApplicationDeleteOne) ExecX(ctx context.Context) {
	gmado.gmad.ExecX(ctx)
}
