// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-boardgame-stats/backend/internal/ent/groupsettings"
	"github.com/open-boardgame-stats/backend/internal/ent/predicate"
)

// GroupSettingsDelete is the builder for deleting a GroupSettings entity.
type GroupSettingsDelete struct {
	config
	hooks    []Hook
	mutation *GroupSettingsMutation
}

// Where appends a list predicates to the GroupSettingsDelete builder.
func (gsd *GroupSettingsDelete) Where(ps ...predicate.GroupSettings) *GroupSettingsDelete {
	gsd.mutation.Where(ps...)
	return gsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gsd *GroupSettingsDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gsd.hooks) == 0 {
		affected, err = gsd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroupSettingsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gsd.mutation = mutation
			affected, err = gsd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gsd.hooks) - 1; i >= 0; i-- {
			if gsd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gsd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gsd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (gsd *GroupSettingsDelete) ExecX(ctx context.Context) int {
	n, err := gsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gsd *GroupSettingsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: groupsettings.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: groupsettings.FieldID,
			},
		},
	}
	if ps := gsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// GroupSettingsDeleteOne is the builder for deleting a single GroupSettings entity.
type GroupSettingsDeleteOne struct {
	gsd *GroupSettingsDelete
}

// Exec executes the deletion query.
func (gsdo *GroupSettingsDeleteOne) Exec(ctx context.Context) error {
	n, err := gsdo.gsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupsettings.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gsdo *GroupSettingsDeleteOne) ExecX(ctx context.Context) {
	gsdo.gsd.ExecX(ctx)
}
