// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-boardgame-stats/backend/internal/ent/playersupervisionrequestapproval"
	"github.com/open-boardgame-stats/backend/internal/ent/predicate"
)

// PlayerSupervisionRequestApprovalDelete is the builder for deleting a PlayerSupervisionRequestApproval entity.
type PlayerSupervisionRequestApprovalDelete struct {
	config
	hooks    []Hook
	mutation *PlayerSupervisionRequestApprovalMutation
}

// Where appends a list predicates to the PlayerSupervisionRequestApprovalDelete builder.
func (psrad *PlayerSupervisionRequestApprovalDelete) Where(ps ...predicate.PlayerSupervisionRequestApproval) *PlayerSupervisionRequestApprovalDelete {
	psrad.mutation.Where(ps...)
	return psrad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (psrad *PlayerSupervisionRequestApprovalDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(psrad.hooks) == 0 {
		affected, err = psrad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PlayerSupervisionRequestApprovalMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			psrad.mutation = mutation
			affected, err = psrad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(psrad.hooks) - 1; i >= 0; i-- {
			if psrad.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = psrad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, psrad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (psrad *PlayerSupervisionRequestApprovalDelete) ExecX(ctx context.Context) int {
	n, err := psrad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (psrad *PlayerSupervisionRequestApprovalDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: playersupervisionrequestapproval.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: playersupervisionrequestapproval.FieldID,
			},
		},
	}
	if ps := psrad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, psrad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// PlayerSupervisionRequestApprovalDeleteOne is the builder for deleting a single PlayerSupervisionRequestApproval entity.
type PlayerSupervisionRequestApprovalDeleteOne struct {
	psrad *PlayerSupervisionRequestApprovalDelete
}

// Exec executes the deletion query.
func (psrado *PlayerSupervisionRequestApprovalDeleteOne) Exec(ctx context.Context) error {
	n, err := psrado.psrad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{playersupervisionrequestapproval.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (psrado *PlayerSupervisionRequestApprovalDeleteOne) ExecX(ctx context.Context) {
	psrado.psrad.ExecX(ctx)
}
