// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/open-boardgame-stats/backend/internal/ent/schema/guidgql"
	"github.com/open-boardgame-stats/backend/internal/ent/schema/stat"
	"github.com/open-boardgame-stats/backend/internal/ent/statdescription"
)

// StatDescription is the model entity for the StatDescription schema.
type StatDescription struct {
	config `json:"-"`
	// ID of the ent.
	ID guidgql.GUID `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type stat.StatType `json:"type,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// PossibleValues holds the value of the "possible_values" field.
	PossibleValues []string `json:"possible_values,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StatDescriptionQuery when eager-loading is set.
	Edges StatDescriptionEdges `json:"edges"`
}

// StatDescriptionEdges holds the relations/edges for other nodes in the graph.
type StatDescriptionEdges struct {
	// Game holds the value of the game edge.
	Game []*Game `json:"game,omitempty"`
	// Stats holds the value of the stats edge.
	Stats []*Statistic `json:"stats,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool

	namedGame  map[string][]*Game
	namedStats map[string][]*Statistic
}

// GameOrErr returns the Game value or an error if the edge
// was not loaded in eager-loading.
func (e StatDescriptionEdges) GameOrErr() ([]*Game, error) {
	if e.loadedTypes[0] {
		return e.Game, nil
	}
	return nil, &NotLoadedError{edge: "game"}
}

// StatsOrErr returns the Stats value or an error if the edge
// was not loaded in eager-loading.
func (e StatDescriptionEdges) StatsOrErr() ([]*Statistic, error) {
	if e.loadedTypes[1] {
		return e.Stats, nil
	}
	return nil, &NotLoadedError{edge: "stats"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StatDescription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case statdescription.FieldPossibleValues:
			values[i] = new([]byte)
		case statdescription.FieldID:
			values[i] = new(guidgql.GUID)
		case statdescription.FieldName, statdescription.FieldDescription:
			values[i] = new(sql.NullString)
		case statdescription.FieldType:
			values[i] = new(stat.StatType)
		default:
			return nil, fmt.Errorf("unexpected column %q for type StatDescription", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StatDescription fields.
func (sd *StatDescription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case statdescription.FieldID:
			if value, ok := values[i].(*guidgql.GUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				sd.ID = *value
			}
		case statdescription.FieldType:
			if value, ok := values[i].(*stat.StatType); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value != nil {
				sd.Type = *value
			}
		case statdescription.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				sd.Name = value.String
			}
		case statdescription.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				sd.Description = value.String
			}
		case statdescription.FieldPossibleValues:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field possible_values", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &sd.PossibleValues); err != nil {
					return fmt.Errorf("unmarshal field possible_values: %w", err)
				}
			}
		}
	}
	return nil
}

// QueryGame queries the "game" edge of the StatDescription entity.
func (sd *StatDescription) QueryGame() *GameQuery {
	return (&StatDescriptionClient{config: sd.config}).QueryGame(sd)
}

// QueryStats queries the "stats" edge of the StatDescription entity.
func (sd *StatDescription) QueryStats() *StatisticQuery {
	return (&StatDescriptionClient{config: sd.config}).QueryStats(sd)
}

// Update returns a builder for updating this StatDescription.
// Note that you need to call StatDescription.Unwrap() before calling this method if this StatDescription
// was returned from a transaction, and the transaction was committed or rolled back.
func (sd *StatDescription) Update() *StatDescriptionUpdateOne {
	return (&StatDescriptionClient{config: sd.config}).UpdateOne(sd)
}

// Unwrap unwraps the StatDescription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sd *StatDescription) Unwrap() *StatDescription {
	_tx, ok := sd.config.driver.(*txDriver)
	if !ok {
		panic("ent: StatDescription is not a transactional entity")
	}
	sd.config.driver = _tx.drv
	return sd
}

// String implements the fmt.Stringer.
func (sd *StatDescription) String() string {
	var builder strings.Builder
	builder.WriteString("StatDescription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sd.ID))
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", sd.Type))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(sd.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(sd.Description)
	builder.WriteString(", ")
	builder.WriteString("possible_values=")
	builder.WriteString(fmt.Sprintf("%v", sd.PossibleValues))
	builder.WriteByte(')')
	return builder.String()
}

// NamedGame returns the Game named value or an error if the edge was not
// loaded in eager-loading with this name.
func (sd *StatDescription) NamedGame(name string) ([]*Game, error) {
	if sd.Edges.namedGame == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := sd.Edges.namedGame[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (sd *StatDescription) appendNamedGame(name string, edges ...*Game) {
	if sd.Edges.namedGame == nil {
		sd.Edges.namedGame = make(map[string][]*Game)
	}
	if len(edges) == 0 {
		sd.Edges.namedGame[name] = []*Game{}
	} else {
		sd.Edges.namedGame[name] = append(sd.Edges.namedGame[name], edges...)
	}
}

// NamedStats returns the Stats named value or an error if the edge was not
// loaded in eager-loading with this name.
func (sd *StatDescription) NamedStats(name string) ([]*Statistic, error) {
	if sd.Edges.namedStats == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := sd.Edges.namedStats[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (sd *StatDescription) appendNamedStats(name string, edges ...*Statistic) {
	if sd.Edges.namedStats == nil {
		sd.Edges.namedStats = make(map[string][]*Statistic)
	}
	if len(edges) == 0 {
		sd.Edges.namedStats[name] = []*Statistic{}
	} else {
		sd.Edges.namedStats[name] = append(sd.Edges.namedStats[name], edges...)
	}
}

// StatDescriptions is a parsable slice of StatDescription.
type StatDescriptions []*StatDescription

func (sd StatDescriptions) config(cfg config) {
	for _i := range sd {
		sd[_i].config = cfg
	}
}
