// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/open-boardgame-stats/backend/internal/ent"
	"github.com/open-boardgame-stats/backend/internal/ent/enums"
	"github.com/open-boardgame-stats/backend/internal/ent/groupsettings"
	"github.com/open-boardgame-stats/backend/internal/ent/schema/guidgql"
)

type CreateOrUpdateGroupInput struct {
	ID          *guidgql.GUID       `json:"id"`
	Name        string              `json:"name"`
	Description *string             `json:"description"`
	LogoURL     string              `json:"logoUrl"`
	Settings    *GroupSettingsInput `json:"settings"`
}

type CreatePlayerInput struct {
	Name string `json:"name"`
}

type Favorites struct {
	Total int         `json:"total"`
	Users []*ent.User `json:"users"`
}

type GroupApplicationInput struct {
	GroupID guidgql.GUID `json:"groupId"`
	Message *string      `json:"message"`
}

type GroupSettingsInput struct {
	Visibility          groupsettings.Visibility `json:"visibility"`
	JoinPolicy          groupsettings.JoinPolicy `json:"joinPolicy"`
	MinimumRoleToInvite *enums.Role              `json:"minimumRoleToInvite"`
}

type RequestPlayerSupervisionInput struct {
	PlayerID guidgql.GUID `json:"playerId"`
	Message  *string      `json:"message"`
}

type ResolvePlayerSupervisionRequestInput struct {
	RequestID guidgql.GUID `json:"requestId"`
	Approved  bool         `json:"approved"`
}
