// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
	"github.com/open-boardgame-stats/backend/internal/ent/enums"
	"github.com/open-boardgame-stats/backend/internal/ent/groupsettings"
)

type CreateGroupInput struct {
	Name                string                   `json:"name"`
	Description         *string                  `json:"description"`
	LogoURL             string                   `json:"logoUrl"`
	Visibility          groupsettings.Visibility `json:"visibility"`
	JoinPolicy          groupsettings.JoinPolicy `json:"joinPolicy"`
	MinimumRoleToInvite *enums.Role              `json:"minimumRoleToInvite"`
}

type CreatePlayerInput struct {
	Name string `json:"name"`
}

type RequestPlayerSupervisionInput struct {
	PlayerID uuid.UUID `json:"playerId"`
	Message  *string   `json:"message"`
}

type ResolvePlayerSupervisionRequestInput struct {
	RequestID uuid.UUID `json:"requestId"`
	Approved  bool      `json:"approved"`
}
