// Code generated by ent, DO NOT EDIT.

package playersupervisionrequestapproval

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the playersupervisionrequestapproval type in the database.
	Label = "player_supervision_request_approval"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldApproved holds the string denoting the approved field in the database.
	FieldApproved = "approved"
	// EdgeApprover holds the string denoting the approver edge name in mutations.
	EdgeApprover = "approver"
	// EdgeSupervisionRequest holds the string denoting the supervision_request edge name in mutations.
	EdgeSupervisionRequest = "supervision_request"
	// Table holds the table name of the playersupervisionrequestapproval in the database.
	Table = "player_supervision_request_approvals"
	// ApproverTable is the table that holds the approver relation/edge.
	ApproverTable = "player_supervision_request_approvals"
	// ApproverInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ApproverInverseTable = "users"
	// ApproverColumn is the table column denoting the approver relation/edge.
	ApproverColumn = "user_supervision_request_approvals"
	// SupervisionRequestTable is the table that holds the supervision_request relation/edge.
	SupervisionRequestTable = "player_supervision_request_approvals"
	// SupervisionRequestInverseTable is the table name for the PlayerSupervisionRequest entity.
	// It exists in this package in order to avoid circular dependency with the "playersupervisionrequest" package.
	SupervisionRequestInverseTable = "player_supervision_requests"
	// SupervisionRequestColumn is the table column denoting the supervision_request relation/edge.
	SupervisionRequestColumn = "player_supervision_request_approvals"
)

// Columns holds all SQL columns for playersupervisionrequestapproval fields.
var Columns = []string{
	FieldID,
	FieldApproved,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "player_supervision_request_approvals"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"player_supervision_request_approvals",
	"user_supervision_request_approvals",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
