name: code

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  code:
    strategy:
      matrix:
        mode:
          - name: Test
            command: go test ./...

          - name: Check generate
            command: .github/scripts/check-generate.sh

      fail-fast: false
    name: ${{ matrix.mode.name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - run: ${{ matrix.mode.command }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 5m
