name: Main

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SCHEMA_DEPLOY_KEY }}
          submodules: recursive
      - run: go test ./...

  check-generate:
    name: Check generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SCHEMA_DEPLOY_KEY }}
          submodules: recursive
      - run: .github/scripts/check-generate.sh
